# Constants for analysis time periods
TIME_PERIOD_SHORT = 10  # 10 days
TIME_PERIOD_MEDIUM = 30  # 30 days
TIME_PERIOD_LONG = 90   # 90 days

# Database placeholders
DEFAULT_RETURN_NO_DATA = 1
DEFAULT_RETURN_NO_CHANGE = 1

PRODUCT_BUCKET_SIZE = 2000

NO_MARKET_PRICE_INCREASE = 1.01 
SHARE_UNDERCUT_PERCENTAGE = 0.995  # Undercut by 0.5%