#
#
# Constants for Sub AIs
#
#

# INDEX CONSTANTS

FIRST = 0
SECOND = 1

# Constants for Products

HIGH_PERCENTAGE_OF_SAVINGS_TO_SPEND = 0.60
HIGH_SPENDING_RANGE_OF_BUCKET_DRAWS = [1,5]
HIGH_CHANCE_TO_SPEND_MONEY = [1,5]


MEDIUM_PERCENTAGE_OF_SAVINGS_TO_SPEND = 0.30
MEDIUM_SPENDING_RANGE_OF_BUCKET_DRAWS = [1,8]
MEDIUM_CHANCE_TO_SPEND_MONEY = [1,3]


LOW_PERCENTAGE_OF_SAVINGS_TO_SPEND = 0.15
LOW_SPENDING_RANGE_OF_BUCKET_DRAWS = [1,15]
LOW_CHANCE_TO_SPEND_MONEY = [1,2]

# Constants for Holding Evalutation

HIGH_PROFIT_GOALS = 0.5
HIGH_LOSS_LIMITS = 0.5
HIGH_SHARE_RAPID_GROWTH_PERCENTAGE_CONFORTABILITY = 0.90
HIGH_REPUTATION_POINT_LOSS_CONFORTABILITY = 300
HIGH_COMPANY_SALES_DECLINE_PERCENTAGE_CONFORTABILITY = 0.75 

MEDIUM_PROFIT_GOALS = 0.25
MEDIUM_LOSS_LIMITS = 0.25
MEDIUM_SHARE_RAPID_GROWTH_PERCENTAGE_CONFORTABILITY = 0.50
MEDIUM_REPUTATION_POINT_LOSS_CONFORTABILITY = 150
MEDIUM_COMPANY_SALES_DECLINE_PERCENTAGE_CONFORTABILITY = 0.50 

LOW_PROFIT_GOALS = 0.10
LOW_LOSS_LIMITS = 0.10
LOW_SHARE_RAPID_GROWTH_PERCENTAGE_CONFORTABILITY = 0.25
LOW_REPUTATION_POINT_LOSS_CONFORTABILITY = 75
LOW_COMPANY_SALES_DECLINE_PERCENTAGE_CONFORTABILITY = 0.25 

# Constants for Share Scoring
HIGH_CONFORMIST_WEIGHT = 0.8
HIGH_CONTRARIAN_WEIGHT = 0.8
HIGH_REPUTATION_WEIGHT = 0.8
HIGH_SHARE_PERFORMANCE_WEIGHT = 0.8
HIGH_COMPANY_PERFORMANCE_WEIGHT = 0.8
HIGH_VALUE_ESTIMATION_WEIGHT = 0.8
HIGH_VOLATILITY_TOLERANCE_WEIGHT = 0.8

MEDIUM_CONFORMIST_WEIGHT = 0.5
MEDIUM_CONTRARIAN_WEIGHT = 0.5
MEDIUM_REPUTATION_WEIGHT = 0.5
MEDIUM_SHARE_PERFORMANCE_WEIGHT = 0.5
MEDIUM_COMPANY_PERFORMANCE_WEIGHT = 0.5
MEDIUM_VALUE_ESTIMATION_WEIGHT = 0.5
MEDIUM_VOLATILITY_TOLERANCE_WEIGHT = 0.5

LOW_CONFORMIST_WEIGHT = 0.2
LOW_CONTRARIAN_WEIGHT = 0.2
LOW_REPUTATION_WEIGHT = 0.2
LOW_SHARE_PERFORMANCE_WEIGHT = 0.2
LOW_COMPANY_PERFORMANCE_WEIGHT = 0.2
LOW_VALUE_ESTIMATION_WEIGHT = 0.2
LOW_VOLATILITY_TOLERANCE_WEIGHT = 0.2

# Other Constants
HIGH_RANDOMNESS_RANGE = [0.8, 1.2]
MEDIUM_RANDOMNESS_RANGE = [0.9, 1.1]
LOW_RANDOMNESS_RANGE = [0.95, 1.05]

HIGH_PORTFOLIO_DIVERSITY_REQUIREMENTS = 0.10
MEDIUM_PORTFOLIO_DIVERSITY_REQUIREMENTS = 0.25
LOW_PORTFOLIO_DIVERSITY_REQUIREMENTS = 0.50

HIGH_HISTORY_SCOPE = 90
MEDIUM_HISTORY_SCOPE = 30
LOW_HISTORY_SCOPE = 10

HIGH_PERCENTAGE_OF_NETWORTH_TO_INVEST = 0.8
MEDIUM_PERCENTAGE_OF_NETWORTH_TO_INVEST = 0.5
LOW_PERCENTAGE_OF_NETWORTH_TO_INVEST = 0.2

HIGH_CHANCE_OF_PREMATURE_SELL_RANGE = [1, 2500]
MEDIUM_CHANCE_OF_PREMATURE_SELL_RANGE = [1, 5000]
LOW_CHANCE_OF_PREMATURE_SELL_RANGE = [1, 10000]